### ISSUE TITLE
SlackerRunner, tests error without error trace for Visual Studio 15.8, culture parse error

### ISSUE THREAD

**Issue by kethahel99** [deloitte-solvas/SlackerRunner#22]
I've setup my Slacker unit tests in SSDT as well as my tinytds database connection to a local SQL Server unit testing database. However I keep getting the below error:

![image](https://user-images.githubusercontent.com/25621492/46981302-15ad6a80-d0d8-11e8-937c-520b6cc4dc7c.png)

Please help?

**Comment by ornatwork** [comment]
Try updating the timeout to a larger value if you have a lot of tests.   The default value is 60 seconds.

**Comment by kethahel99** [comment]
Hi there. Turned out it was my databases connection 

Now I get a new error when running tests:
Input string was not in a correct format.

This happens when the SlackerService().Run method tries to load files from directory.

Any ideas?
I'm using basic samples from generated slacker_new  project

**Comment by ornatwork** [comment]
Did you update \SlackerTests\database.yml to point to your database ? what does it look like ?

**Comment by kethahel99** [comment]
Yes, my database.yml settings are below and connection works fine


# Database connection.

# Slacker supports odbc and tiny_tds.
# When not set, driver defaults to odbc for backward compatibility.
# The odbc driver is easier to set up on Windows, but tiny_tds is recommended
# if you intend to run slacker cross-platform.
# See https://github.com/vassilvk/slacker/wiki/Slacker-Project#odbc-vs-tds for more information.
driver: odbc

# Full instance name when using odbc; hostname or IP when using tiny_tds.
server: localhost

# Port is used by tiny_tds only. Defaults to 1433 when not set.
# Use server and port when targeting named instances with tiny_tds.
port: 1433

# The target database.
database: DataReservoirDevOps

# Slacker supports only SQL Server authentication.
user: unittest
password: Testing123

# Set this to false when using alternative formatters such as -fh and fj.
console_enabled: true

**Comment by kethahel99** [comment]
Oh and yes, the project is here:
https://github.com/kethahel99/SlackerTest

**Comment by kethahel99** [comment]
[16/10/2018 23:27:31 PM Error] [xUnit.net 00:00:09.68]     DatabaseUnittests.AllTestSpecs.runSpecsIndividually(File: sample_1.rb) [FAIL]
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68]       System.FormatException : Input string was not in a correct format.
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68]       Stack Trace:
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68]            at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68]            at SlackerRunner.ResultsParser.Parse(String result, String standardError)
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68]            at SlackerRunner.ProfileRunner.Run(String testDirectory, String testFile)
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68]            at SlackerRunner.SlackerService.Run(String testdirectory, String specfile)

**Comment by kethahel99** [comment]
Any ideas @ornatwork ?

**Comment by ornatwork** [comment]
I got your project, unfortunately it works fine when I run it locally.  I'm suspecting that some test data got mangled on your local.  If you remove the sample1_rb temporarily from the directory, do the others tests run fine ?

**Comment by kethahel99** [comment]
Thanks @ornatwork , I will try these recommendations.
I have 4 rpsec files in my spec folder and they all give this error: 
[16/10/2018 23:27:31 PM Informational] [xUnit.net 00:00:09.68] System.FormatException : Input string was not in a correct format.


But let me remove them and re-add

**Comment by kethahel99** [comment]
I've tried that now and I still get this:

[17/10/2018 20:56:21 PM Error] [xUnit.net 00:00:02.64]     DatabaseUnittests.AllTestSpecs.runSpecsIndividually(File: sample_1.rb) [FAIL]
[17/10/2018 20:56:21 PM Informational] [xUnit.net 00:00:02.64]       System.FormatException : Input string was not in a correct format.

**Comment by ornatwork** [comment]
I see you are using the latest SlackerRunner that is good.  Try Slacker from the command line on your local in \DataReservoirDevOps\TestSpecs, run this command "Slacker" without the quotes, what is the output you get ?

**Comment by ornatwork** [comment]
Yes something strange going on here.  We have seen a lot of issues with SSDT in VS 2017 15.8.  If you are on that version please downgrade to a known stable 15.7.6 - https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017

**Comment by kethahel99** [comment]
Good plan, I will try that. At least we know slacker works fine. I will downgrade and test again.

Thanks!

**Comment by kethahel99** [comment]
Hi @ornatwork 

I've tested with Visual Studio 15.7.6 and I still get the below error:

![image](https://user-images.githubusercontent.com/25621492/47323473-3b002280-d65c-11e8-9974-f14afd35f334.png)

**Comment by kethahel99** [comment]
[23/10/2018 00:37:40 AM Informational] ------ Discover test started ------
[23/10/2018 00:37:45 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (32-bit Universal Windows)
[23/10/2018 00:37:45 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (32-bit Desktop .NET 4.0.30319.42000)
[23/10/2018 00:37:45 AM Informational] ========== Discover test finished: 0 found (0:00:04,9329441) ==========
[23/10/2018 00:38:18 AM Informational] ------ Discover test started ------
[23/10/2018 00:38:19 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (32-bit Universal Windows)
[23/10/2018 00:38:19 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (32-bit Desktop .NET 4.0.30319.42000)
[23/10/2018 00:38:19 AM Informational] ========== Discover test finished: 0 found (0:00:01,1775642) ==========
[23/10/2018 00:38:19 AM Informational] ------ Run test started ------
[23/10/2018 00:38:20 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (32-bit Universal Windows)
[23/10/2018 00:38:20 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (32-bit Desktop .NET 4.0.30319.42000)
[23/10/2018 00:38:21 AM Informational] [xUnit.net 00:00:00.68]   Discovering: DatabaseUnitTest
[23/10/2018 00:38:21 AM Informational] [xUnit.net 00:00:01.05]   Discovered:  DatabaseUnitTest
[23/10/2018 00:38:21 AM Informational] [xUnit.net 00:00:01.05]   Starting:    DatabaseUnitTest
[23/10/2018 00:38:23 AM Error] [xUnit.net 00:00:03.27]     DatabaseUnittest.AllTestSpecs.RunAll(File: sample_1.rb) [FAIL]
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]       System.FormatException : Input string was not in a correct format.
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]       Stack Trace:
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]            at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]            at SlackerRunner.ResultsParser.Parse(String result, String standardError)
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]            at SlackerRunner.ProfileRunner.Run(String testDirectory, String testFile)
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]            at SlackerRunner.SlackerService.Run(String testdirectory, String specfile)
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.27]         D:\Source\Repos\ReservoirDemo\DataReservoirDevOps\DatabaseUnitTest\AllTestSpecs.cs(21,0): at DatabaseUnittest.AllTestSpecs.RunAll(ISpecTestFile File)
[23/10/2018 00:38:23 AM Informational] [xUnit.net 00:00:03.29]   Finished:    DatabaseUnitTest
[23/10/2018 00:38:24 AM Informational] ========== Run test finished: 1 run (0:00:04,8582863) ==========

**Comment by kethahel99** [comment]
It looks like the error is triggered while attempting to parse the test results:
[23/10/2018 00:44:06 AM Informational] [xUnit.net 00:00:03.18]       System.FormatException : Input string was not in a correct format.
[23/10/2018 00:44:06 AM Informational] [xUnit.net 00:00:03.18]       Stack Trace:
[23/10/2018 00:44:06 AM Informational] [xUnit.net 00:00:03.18]            at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
[23/10/2018 00:44:06 AM Informational] [xUnit.net 00:00:03.18]            at SlackerRunner.ResultsParser.Parse(String result, String standardError)
[23/10/2018 00:44:06 AM Informational] [xUnit.net 00:00:03.18]            at SlackerRunner.ProfileRunner.Run(String testDirectory, String testFile)
[23/10/2018 00:44:06 AM Informational] [xUnit.net 00:00:03.18]            at SlackerRunner.SlackerService.Run(String testdirectory, String specfile)


I can see the tests actually run and if you open the .sql files you can see the results.
![image](https://user-images.githubusercontent.com/25621492/47323636-ec06bd00-d65c-11e8-9690-31fb10e30195.png)

The problem is that the results are not parsed correctly and returned to Visual Studio's Test Explorer

**Comment by kethahel99** [comment]
Hi @ornatwork ,

I think I found the issue. As per my previous notes above, the tests run successfully but the problem comes in when SlackerRunner.ResultsParser is trying to convert certain string (seconds) values from string to double here:
![image](https://user-images.githubusercontent.com/25621492/47351823-171efa00-d6b9-11e8-8b3c-ccc216bc1ff2.png)


The reason why you could not reproduce the issue is because you regional settings might be different to mine.

So I tried changing the double.parse code to make it culture insensitive here:

![image](https://user-images.githubusercontent.com/25621492/47351920-42094e00-d6b9-11e8-8e5d-98b831325c30.png)


I referenced the fixed build in my unit test project and low and behold it works!
![image](https://user-images.githubusercontent.com/25621492/47352106-8e548e00-d6b9-11e8-92d1-03b9c8cf956d.png)

I will issue a PR and reference here

**Comment by kethahel99** [comment]
P.S another options is to not use culture insensitivity and just use the current regional settings like this:

      return string.IsNullOrEmpty(match) ? 0 : double.Parse(match, CultureInfo.CurrentCulture);

**Comment by kethahel99** [comment]
Do I have to fork first, and then do a PR?

**Comment by ornatwork** [comment]
That's great news.  Yes fork and PR, that would be great, I can promote it right away.  Thanks for doing the research, you rock !

**Comment by ornatwork** [comment]
Your fix has been pushed - 2.5.0.7 - https://www.nuget.org/packages/SlackerRunner/

Thanks !

**Comment by kethahel99** [comment]
Awesome! Thanks!
