### ISSUE TITLE
Trace from tests when run by msTest runner

### ISSUE THREAD

**Issue by ornatwork** [deloitte-solvas/SlackerRunner#4]
When run under MsTest runner no trace is available from Visual Studio or TFS anymore.

**Comment by ornatwork** [comment]
Fixed with version 2.0.0.14, in VS go to the output Debug and you can see the traces / stack traces there.  Something as seen below 

Sample, good test output
------------------------------------------------------------------
~~~ Slacker runner, version=2.0.0.14
~~~ process ended, exitcode=0
~~~ process standard out=Beachcomber (local_dev)
.

Finished in 0.05604 seconds (files took 1.36 seconds to load)
1 example, 0 failures
-------------------------------------------------------------------


Sample failure test output
-------------------------------------------------------------------
~~~ Slacker runner, version=2.0.0.14
~~~ process ended, exitcode=0
~~~ process standard out=Beachcomber (local_dev)
F

Failures:

  1) bc.ConfigValueCodePart works as expected
     Failure/Error: s_func('bc.ConfigValueCodePart', config_value, part).should == expected

       expected: "abc"
            got: "1abc" (using ==)
     # ./spec/config/config_value_code_part.rb:15:in `test_value_part'
     # ./spec/config/config_value_code_part.rb:19:in `block (2 levels) in <top (required)>'

Finished in 0.34425 seconds (files took 0.62449 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/config/config_value_code_part.rb:18 # bc.ConfigValueCodePart works as expected
-------------------------------------------------------------------
